/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sKubernetesPkgApiV1LoadBalancerStatus;
import java.io.IOException;

/**
 * ServiceStatus represents the current status of a service.
 */
@ApiModel(description = "ServiceStatus represents the current status of a service.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-16T15:42:22.208Z")
public class IoK8sKubernetesPkgApiV1ServiceStatus {
  @SerializedName("loadBalancer")
  private IoK8sKubernetesPkgApiV1LoadBalancerStatus loadBalancer = null;

  public IoK8sKubernetesPkgApiV1ServiceStatus loadBalancer(IoK8sKubernetesPkgApiV1LoadBalancerStatus loadBalancer) {
    this.loadBalancer = loadBalancer;
    return this;
  }

   /**
   * LoadBalancer contains the current status of the load-balancer, if one is present.
   * @return loadBalancer
  **/
  @ApiModelProperty(value = "LoadBalancer contains the current status of the load-balancer, if one is present.")
  public IoK8sKubernetesPkgApiV1LoadBalancerStatus getLoadBalancer() {
    return loadBalancer;
  }

  public void setLoadBalancer(IoK8sKubernetesPkgApiV1LoadBalancerStatus loadBalancer) {
    this.loadBalancer = loadBalancer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sKubernetesPkgApiV1ServiceStatus ioK8sKubernetesPkgApiV1ServiceStatus = (IoK8sKubernetesPkgApiV1ServiceStatus) o;
    return Objects.equals(this.loadBalancer, ioK8sKubernetesPkgApiV1ServiceStatus.loadBalancer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadBalancer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sKubernetesPkgApiV1ServiceStatus {\n");
    
    sb.append("    loadBalancer: ").append(toIndentedString(loadBalancer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

