/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import io.swagger.client.model.IoK8sKubernetesPkgApisAuthorizationV1LocalSubjectAccessReview;
import io.swagger.client.model.IoK8sKubernetesPkgApisAuthorizationV1SelfSubjectAccessReview;
import io.swagger.client.model.IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReview;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthorizationV1Api
 */
@Ignore
public class AuthorizationV1ApiTest {

    private final AuthorizationV1Api api = new AuthorizationV1Api();

    
    /**
     * 
     *
     * create a LocalSubjectAccessReview
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAuthorizationV1NamespacedLocalSubjectAccessReviewTest() throws ApiException {
        String namespace = null;
        IoK8sKubernetesPkgApisAuthorizationV1LocalSubjectAccessReview body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisAuthorizationV1LocalSubjectAccessReview response = api.createAuthorizationV1NamespacedLocalSubjectAccessReview(namespace, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a SelfSubjectAccessReview
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAuthorizationV1SelfSubjectAccessReviewTest() throws ApiException {
        IoK8sKubernetesPkgApisAuthorizationV1SelfSubjectAccessReview body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisAuthorizationV1SelfSubjectAccessReview response = api.createAuthorizationV1SelfSubjectAccessReview(body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create a SubjectAccessReview
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAuthorizationV1SubjectAccessReviewTest() throws ApiException {
        IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReview body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisAuthorizationV1SubjectAccessReview response = api.createAuthorizationV1SubjectAccessReview(body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAuthorizationV1APIResourcesTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIResourceList response = api.getAuthorizationV1APIResources();

        // TODO: test validations
    }
    
}
