/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1DeleteOptions;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Patch;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Status;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1WatchEvent;
import io.swagger.client.model.IoK8sKubernetesPkgApisStorageV1beta1StorageClass;
import io.swagger.client.model.IoK8sKubernetesPkgApisStorageV1beta1StorageClassList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StorageV1beta1Api
 */
@Ignore
public class StorageV1beta1ApiTest {

    private final StorageV1beta1Api api = new StorageV1beta1Api();

    
    /**
     * 
     *
     * create a StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createStorageV1beta1StorageClassTest() throws ApiException {
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass response = api.createStorageV1beta1StorageClass(body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStorageV1beta1CollectionStorageClassTest() throws ApiException {
        String pretty = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteStorageV1beta1CollectionStorageClass(pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStorageV1beta1StorageClassTest() throws ApiException {
        String name = null;
        IoK8sApimachineryPkgApisMetaV1DeleteOptions body = null;
        String pretty = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        String propagationPolicy = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteStorageV1beta1StorageClass(name, body, pretty, gracePeriodSeconds, orphanDependents, propagationPolicy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStorageV1beta1APIResourcesTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIResourceList response = api.getStorageV1beta1APIResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list or watch objects of kind StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStorageV1beta1StorageClassTest() throws ApiException {
        String pretty = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClassList response = api.listStorageV1beta1StorageClass(pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchStorageV1beta1StorageClassTest() throws ApiException {
        String name = null;
        IoK8sApimachineryPkgApisMetaV1Patch body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass response = api.patchStorageV1beta1StorageClass(name, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readStorageV1beta1StorageClassTest() throws ApiException {
        String name = null;
        String pretty = null;
        Boolean exact = null;
        Boolean export = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass response = api.readStorageV1beta1StorageClass(name, pretty, exact, export);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceStorageV1beta1StorageClassTest() throws ApiException {
        String name = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass body = null;
        String pretty = null;
        IoK8sKubernetesPkgApisStorageV1beta1StorageClass response = api.replaceStorageV1beta1StorageClass(name, body, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * watch changes to an object of kind StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watchStorageV1beta1StorageClassTest() throws ApiException {
        String name = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1WatchEvent response = api.watchStorageV1beta1StorageClass(name, fieldSelector, includeUninitialized, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * watch individual changes to a list of StorageClass
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watchStorageV1beta1StorageClassListTest() throws ApiException {
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1WatchEvent response = api.watchStorageV1beta1StorageClassList(fieldSelector, includeUninitialized, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
}
